server:
   port: 8000

spring:

   application:
    name: bookmygift-jdbc
   
   profiles:
    active: jdbc

   cloud:
    config:
      uri: http://localhost:8000
      profile: jdbc
      label: master
      server:
        jdbc:
          sql: "SELECT key, value from myapp.CONFIG_PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?"
          order: 1

   datasource:
      url: jdbc:postgresql://localhost:5432/myuser?currentSchema=myapp
      username: myuser
      password: mypassword

   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
 
   rabbitmq:
      host: localhost
      port: 5672
      username: admin
      password: password
   
   mail:
      host: ${mail.host:}
      port: ${mail.port:}
      username: ${mail.username:}
      password: ${mail.password:}
      properties.mail.smtp.auth: ${mail.properties.mail.smtp.auth:}
      properties.mail.smtp.starttls.enable: ${mail.properties.mail.smtp.starttls.enable:}

management:
   endpoints:
      web:
         exposure:
            include: "*"
   health:
      show-details: always
      
logging:
   pattern:
      file: '%d{yyyy-MM-dd HH:mm:ss,SSS} %5p [%t] %c [%M] - %m%n'
   level:
      com.bookmygift: DEBUG
      org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG